### ISSUE TITLE
About 25-75% deviation over five random seeds

### ISSUE THREAD

**Issue by minglou1984** [mansicer/MAIC#4]
In this paper, Section in "Experimental Results"
![image](https://user-images.githubusercontent.com/37362398/198177497-f760b747-dd42-45bf-b15b-6a2091c2257c.png)
what is 25%-75% deviation?
Can you give a simple example？

**Comment by mansicer** [comment]
Sorry for the ambiguity. Actually, our figure curves are plotted with a solid line standing for the average performance (e.g., the average test win rate), and a shaded region standing for the 25%-75% performance interval from all running seeds. To be more precise, letting `Q = (max - min) / 4`, the interval will be `[min + Q, max - Q]`.

Thanks for your attention to our work!

**Comment by minglou1984** [comment]
Ok, I see what you mean, so the shaded region has nothing to do with variance, but only with the max and min of the data. Is that so?

**Comment by mansicer** [comment]
Yes. We draw the shaded region according to the min and max performances but not the variance, similar to some related works like QPLEX. We believe that this can delineate stability of all methods with better readability of figures.

**Comment by minglou1984** [comment]
Thank you very much for your answer. zongzhang zhang, yang yu and chongjie zhang are all masters in the field of multi agent reinforcement learning. I will keep an eye on your research.

**Comment by mansicer** [comment]
We sincerely thank for your attention. It will be nice if you like MAIC and our other works. We will close this issue since it seems not to be other questions, but further comments are still welcome if other questions exist.

**Comment by minglou1984** [comment]
Hello, regarding the 25%-75% percentile, I still have some questions and I hope you can provide me with an answer.

Firstly, the performance curve is plotted based on the minimum and maximum values, and this method is indeed better than using standard deviation to describe the stability of a method.

Recently, I also plan to use the 25%-75% percentile to plot the shaded area instead of using standard deviation when drawing graphs. This requires the maximum and minimum values of the original data, but I found that all the log data recorded in the pymarl code library are mean and standard deviation.

So I have a question, whether it is necessary to add code to record the maximum and minimum values, or whether some data conversion can be performed on the original tensorboard log file.

**Comment by mansicer** [comment]
Hi, there! I remember that we leave an implementation of logging the median return in the runners. For other metrics like the wining rate, you can also modify corresponding code in the `episode_runner` to realize this. 

https://github.com/mansicer/MAIC/blob/84e3e2c269097ae50d2cb5385a99989116086f96/src/runners/episode_runner.py#L117

However, I may clarify this issue more clearly. Our median calculation and the shaded area are aggregated among different seeds, rather than among test episodes in one seed. In fact, we use the current pymarl logging to get the mean of battle win rate for each seed, and then calculate the median (and also the min & max values) of different runs. That's how we acquire our plots in the paper. 

Huge thanks for your interest to our work.

**Comment by minglou1984** [comment]
Huge thanks for your answer to me, this answer helped me a lot.
